#!/usr/bin/env bash
# Apply Claude Code API modes and persist to ~/.config/claude-menu.generated.sh (sourced, not executed).
# Requires: claude-menu-env.sh (CLAUDE_MENU_ROOT) before this file.

# shellcheck disable=SC1091
source "$CLAUDE_MENU_ROOT/lib/claude-menu-constants.sh"

claude_menu_apply_mode_to_shell() {
    local mode="$1"
    case "$mode" in
        1)
            export CLAUDE_MENU_MODE="direct"
            export ANTHROPIC_BASE_URL="$CLAUDE_MENU_URL_DIRECT"
            export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="0"
            export API_TIMEOUT_MS="$CLAUDE_MENU_API_TIMEOUT_MS"
            unset ANTHROPIC_DEFAULT_HAIKU_MODEL
            unset ANTHROPIC_DEFAULT_SONNET_MODEL
            unset ANTHROPIC_DEFAULT_OPUS_MODEL
            unset CLAUDE_ENABLED_PLUGINS
            unset CLAUDE_EXTRA_KNOWN_MARKETPLACES
            ;;
        2)
            export CLAUDE_MENU_MODE="zai"
            export ANTHROPIC_BASE_URL="$CLAUDE_MENU_URL_ZAI"
            export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1"
            export API_TIMEOUT_MS="$CLAUDE_MENU_API_TIMEOUT_MS"
            export ANTHROPIC_DEFAULT_HAIKU_MODEL="${ANTHROPIC_DEFAULT_HAIKU_MODEL:-$CLAUDE_MENU_ZAI_DEFAULT_HAIKU}"
            export ANTHROPIC_DEFAULT_SONNET_MODEL="${ANTHROPIC_DEFAULT_SONNET_MODEL:-$CLAUDE_MENU_ZAI_DEFAULT_SONNET}"
            export ANTHROPIC_DEFAULT_OPUS_MODEL="${ANTHROPIC_DEFAULT_OPUS_MODEL:-$CLAUDE_MENU_ZAI_DEFAULT_OPUS}"
            export CLAUDE_ENABLED_PLUGINS="$CLAUDE_MENU_ZAI_PLUGINS_JSON"
            if [[ -n "${ZAI_CLAUDE_EXTRA_KNOWN_MARKETPLACES:-}" ]]; then
                export CLAUDE_EXTRA_KNOWN_MARKETPLACES="$ZAI_CLAUDE_EXTRA_KNOWN_MARKETPLACES"
            else
                unset CLAUDE_EXTRA_KNOWN_MARKETPLACES
            fi
            ;;
        3)
            export CLAUDE_MENU_MODE="pro"
            unset ANTHROPIC_BASE_URL
            unset API_TIMEOUT_MS
            unset ANTHROPIC_DEFAULT_HAIKU_MODEL
            unset ANTHROPIC_DEFAULT_SONNET_MODEL
            unset ANTHROPIC_DEFAULT_OPUS_MODEL
            unset CLAUDE_ENABLED_PLUGINS
            unset CLAUDE_EXTRA_KNOWN_MARKETPLACES
            unset CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC
            # API keys override subscription (see Anthropic env docs: ANTHROPIC_API_KEY and bearer token).
            unset ANTHROPIC_AUTH_TOKEN
            unset ANTHROPIC_API_KEY
            ;;
        *)
            echo "claude-menu-modes: unknown mode: $mode" >&2
            return 1
            ;;
    esac
}

claude_menu_write_generated() {
    local mode="$1"
    local out="${CLAUDE_MENU_GENERATED:-$HOME/.config/claude-menu.generated.sh}"
    local dir tmp
    dir="$(dirname "$out")"
    mkdir -p "$dir"
    tmp="$(mktemp "${TMPDIR:-/tmp}/claude-menu-gen.XXXXXX")"
    chmod 600 "$tmp" 2>/dev/null || true

    local title menu_mode
    case "$mode" in
        1) title="anthropic-direct"; menu_mode="direct" ;;
        2) title="zai"; menu_mode="zai" ;;
        3) title="claude-pro"; menu_mode="pro" ;;
        *)
            echo "claude-menu: internal error: unknown generated mode: $mode" >&2
            rm -f "$tmp"
            return 1
            ;;
    esac

    {
        echo "# Generated by claude-menu — do not edit (mode: $title)"
        echo "export CLAUDE_MENU_MODE=$menu_mode"

        case "$mode" in
            1)
                echo "export ANTHROPIC_BASE_URL=\"$CLAUDE_MENU_URL_DIRECT\""
                echo "export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=\"0\""
                echo "export API_TIMEOUT_MS=\"$CLAUDE_MENU_API_TIMEOUT_MS\""
                ;;
            2)
                echo "export ANTHROPIC_BASE_URL=\"$CLAUDE_MENU_URL_ZAI\""
                echo "export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=\"1\""
                echo "export API_TIMEOUT_MS=\"$CLAUDE_MENU_API_TIMEOUT_MS\""
                printf 'export ANTHROPIC_DEFAULT_HAIKU_MODEL=%q\n' "${ANTHROPIC_DEFAULT_HAIKU_MODEL:-$CLAUDE_MENU_ZAI_DEFAULT_HAIKU}"
                printf 'export ANTHROPIC_DEFAULT_SONNET_MODEL=%q\n' "${ANTHROPIC_DEFAULT_SONNET_MODEL:-$CLAUDE_MENU_ZAI_DEFAULT_SONNET}"
                printf 'export ANTHROPIC_DEFAULT_OPUS_MODEL=%q\n' "${ANTHROPIC_DEFAULT_OPUS_MODEL:-$CLAUDE_MENU_ZAI_DEFAULT_OPUS}"
                printf 'export CLAUDE_ENABLED_PLUGINS=%q\n' "$CLAUDE_MENU_ZAI_PLUGINS_JSON"
                if [[ -n "${CLAUDE_EXTRA_KNOWN_MARKETPLACES:-}" ]]; then
                    printf 'export CLAUDE_EXTRA_KNOWN_MARKETPLACES=%q\n' "$CLAUDE_EXTRA_KNOWN_MARKETPLACES"
                fi
                ;;
            3)
                echo "unset ANTHROPIC_BASE_URL"
                echo "unset API_TIMEOUT_MS"
                echo "unset CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC"
                echo "unset ANTHROPIC_AUTH_TOKEN"
                echo "unset ANTHROPIC_API_KEY"
                ;;
        esac

        # Clear unused specific configuration depending on mode
        if [[ "$mode" != 2 ]]; then
            echo "unset ANTHROPIC_DEFAULT_HAIKU_MODEL"
            echo "unset ANTHROPIC_DEFAULT_SONNET_MODEL"
            echo "unset ANTHROPIC_DEFAULT_OPUS_MODEL"
            echo "unset CLAUDE_ENABLED_PLUGINS"
        fi

        if [[ "$mode" != 2 ]] || [[ -z "${CLAUDE_EXTRA_KNOWN_MARKETPLACES:-}" ]]; then
            echo "unset CLAUDE_EXTRA_KNOWN_MARKETPLACES"
        fi
    } >"$tmp"

    mv -f "$tmp" "$out"
    chmod 600 "$out" 2>/dev/null || true
}

claude_menu_set_mode() {
    local mode="$1"
    claude_menu_apply_mode_to_shell "$mode"
    claude_menu_write_generated "$mode"
}

# Apply Z.ai (mode 2) with a named GLM preset for Haiku / Sonnet / Opus slots.
# Presets: default (4.7 family) | glm5
claude_menu_set_zai_model_preset() {
    local preset="$1"
    case "$preset" in
        default | 4.7)
            export ANTHROPIC_DEFAULT_HAIKU_MODEL="$CLAUDE_MENU_ZAI_DEFAULT_HAIKU"
            export ANTHROPIC_DEFAULT_SONNET_MODEL="$CLAUDE_MENU_ZAI_DEFAULT_SONNET"
            export ANTHROPIC_DEFAULT_OPUS_MODEL="$CLAUDE_MENU_ZAI_DEFAULT_OPUS"
            ;;
        glm5 | 5)
            export ANTHROPIC_DEFAULT_HAIKU_MODEL="$CLAUDE_MENU_ZAI_PRESET_GLM5_HAIKU"
            export ANTHROPIC_DEFAULT_SONNET_MODEL="$CLAUDE_MENU_ZAI_PRESET_GLM5_SONNET"
            export ANTHROPIC_DEFAULT_OPUS_MODEL="$CLAUDE_MENU_ZAI_PRESET_GLM5_OPUS"
            ;;
        *)
            echo "claude-menu-modes: unknown Z.ai preset: $preset" >&2
            return 1
            ;;
    esac
    claude_menu_set_mode 2
}

claude_menu_print_persist_hint() {
    echo "💾 Saved as default for new terminals: ${CLAUDE_MENU_GENERATED:-$HOME/.config/claude-menu.generated.sh}"
    echo "   If ~/.zshrc sources claude-menu-shell-env, new tabs inherit this mode (see README)."
}

# Used by claude-switch after claude_menu_set_mode / claude_menu_set_zai_model_preset.
claude_menu_print_switch_done() {
    local usage="$1"
    echo "✅ Claude now configured for: $usage"
    claude_menu_print_persist_hint
    echo "🚀 Start claude with: claude"
}
