#!/usr/bin/env bash
# Non-interactive smoke tests: bash syntax + lib/modes behaviour in an isolated HOME.
# Run from repo root: ./scripts/test-smoke.sh
# Or: bun run test

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FAILED=0

die() {
    echo "FAIL: $*" >&2
    FAILED=1
}

echo "== Syntax (bash -n) =="
SH_FILES=(
    "$ROOT/bin/claude-menu"
    "$ROOT/bin/claude-switch"
    "$ROOT/bin/claude-menu-shell-env"
    "$ROOT/bin/claude-menu-setup"
    "$ROOT/lib/claude-menu-env.sh"
    "$ROOT/lib/claude-menu-constants.sh"
    "$ROOT/lib/claude-menu-modes.sh"
    "$ROOT/scripts/setup.sh"
    "$ROOT/scripts/keychain-store-token.sh"
)
for f in "${SH_FILES[@]}"; do
    if [[ ! -f "$f" ]]; then
        echo "  SKIP missing $f"
        continue
    fi
    bash -n "$f" || die "bash -n $f"
    echo "  OK $(basename "$f")"
done

if command -v shellcheck &>/dev/null; then
    echo ""
    echo "== shellcheck (optional) =="
    for f in "${SH_FILES[@]}"; do
        [[ -f "$f" ]] || continue
        shellcheck -x "$f" && echo "  OK $(basename "$f")" || die "shellcheck $f"
    done
else
    echo ""
    echo "== shellcheck: skipped (install for stricter checks) =="
fi

echo ""
echo "== lib: isolated HOME (env, apply_shell_env, set_mode) =="
TEST_HOME="$(mktemp -d "${TMPDIR:-/tmp}/claude-menu-test.XXXXXX")"
cleanup() { rm -rf "$TEST_HOME"; }
trap cleanup EXIT

export HOME="$TEST_HOME"
mkdir -p "$HOME/.config"
export CLAUDE_MENU_CONFIG="$HOME/.config/claude-menu.env"
: >"$CLAUDE_MENU_CONFIG"
export CLAUDE_MENU_GENERATED="$HOME/.config/claude-menu.generated.sh"
export ANTHROPIC_AUTH_TOKEN="smoke-test-token"

# shellcheck disable=SC1091
source "$ROOT/lib/claude-menu-env.sh"
# shellcheck disable=SC1091
source "$ROOT/lib/claude-menu-modes.sh"

unset CLAUDE_MENU_GENERATED
claude_menu_apply_shell_env
[[ "${CLAUDE_MENU_GENERATED:-}" == "$HOME/.config/claude-menu.generated.sh" ]] || die "apply_shell_env default CLAUDE_MENU_GENERATED path"
echo "  OK claude_menu_apply_shell_env"

claude_menu_set_mode 1
[[ "${ANTHROPIC_BASE_URL:-}" == "$CLAUDE_MENU_URL_DIRECT" ]] || die "mode 1 ANTHROPIC_BASE_URL"
[[ "${API_TIMEOUT_MS:-}" == "$CLAUDE_MENU_API_TIMEOUT_MS" ]] || die "mode 1 API_TIMEOUT_MS"
[[ -f "$CLAUDE_MENU_GENERATED" ]] || die "mode 1 generated file missing"
echo "  OK set_mode 1 (Anthropic)"

export ANTHROPIC_AUTH_TOKEN="smoke-test-token"
claude_menu_set_mode 2
[[ "${ANTHROPIC_BASE_URL:-}" == "$CLAUDE_MENU_URL_ZAI" ]] || die "mode 2 URL"
[[ -n "${ANTHROPIC_DEFAULT_HAIKU_MODEL:-}" ]] || die "mode 2 models"
echo "  OK set_mode 2 (ZAI)"

claude_menu_set_zai_model_preset glm5
[[ "${ANTHROPIC_DEFAULT_SONNET_MODEL:-}" == "glm-5" ]] || die "preset glm5 sonnet"
grep -q 'glm-5' "$CLAUDE_MENU_GENERATED" || die "preset glm5 generated file"
echo "  OK set_zai_model_preset glm5"

export ANTHROPIC_API_KEY="smoke-api-key"
claude_menu_set_mode 3
[[ -z "${ANTHROPIC_BASE_URL:-}" ]] || die "mode 3 BASE_URL unset"
[[ -z "${ANTHROPIC_AUTH_TOKEN:-}" ]] || die "mode 3 must unset ANTHROPIC_AUTH_TOKEN (Claude Pro uses subscription, not API token)"
[[ -z "${ANTHROPIC_API_KEY:-}" ]] || die "mode 3 must unset ANTHROPIC_API_KEY (overrides subscription per Anthropic docs)"
[[ "${CLAUDE_MENU_MODE:-}" == "pro" ]] || die "mode 3 sets CLAUDE_MENU_MODE=pro"
echo "  OK set_mode 3 (Pro)"

echo ""
echo "== lib: Pro mode — reload must not restore API token =="
printf '%s\n' 'export ANTHROPIC_AUTH_TOKEN="from-env-file"' 'export ANTHROPIC_API_KEY="from-env-api-key"' >"$CLAUDE_MENU_CONFIG"
export ANTHROPIC_AUTH_TOKEN="from-env-file"
export ANTHROPIC_API_KEY="from-env-api-key"
# shellcheck disable=SC1090
source "$CLAUDE_MENU_GENERATED"
[[ "${CLAUDE_MENU_MODE:-}" == "pro" ]] || die "generated should set CLAUDE_MENU_MODE=pro"
claude_menu_reload_credentials
[[ -z "${ANTHROPIC_AUTH_TOKEN:-}" ]] || die "Pro reload must leave ANTHROPIC_AUTH_TOKEN unset (Claude Code subscription)"
[[ -z "${ANTHROPIC_API_KEY:-}" ]] || die "Pro reload must leave ANTHROPIC_API_KEY unset"
echo "  OK reload_credentials respects Pro (no API token in shell)"

grep -q 'unset ANTHROPIC_API_KEY' "$CLAUDE_MENU_GENERATED" || die "generated Pro mode should unset ANTHROPIC_API_KEY"

echo ""
echo "== lib: legacy Pro generated (comment only) + reload =="
printf '%s\n' 'export ANTHROPIC_AUTH_TOKEN="legacy-env-token"' >"$CLAUDE_MENU_CONFIG"
printf '%s\n' \
    '# Generated by claude-menu — do not edit (mode: claude-pro)' \
    'unset ANTHROPIC_BASE_URL' \
    'unset ANTHROPIC_AUTH_TOKEN' >"$CLAUDE_MENU_GENERATED"
unset CLAUDE_MENU_MODE
claude_menu_load_generated
[[ "${CLAUDE_MENU_MODE:-}" == "pro" ]] || die "legacy comment should imply CLAUDE_MENU_MODE=pro"
claude_menu_reload_credentials
[[ -z "${ANTHROPIC_AUTH_TOKEN:-}" ]] || die "legacy Pro + reload must not expose API token"
printf '%s\n' 'export ANTHROPIC_API_KEY="legacy-api-key"' >>"$CLAUDE_MENU_CONFIG"
claude_menu_reload_credentials
[[ -z "${ANTHROPIC_API_KEY:-}" ]] || die "legacy Pro + reload must not expose ANTHROPIC_API_KEY"
echo "  OK legacy claude-pro generated file"

if [[ "$FAILED" -ne 0 ]]; then
    echo "" >&2
    echo "Smoke tests failed." >&2
    exit 1
fi

echo ""
echo "All smoke checks passed."
